title: "Scotts Quality Blog"
description: "SEO optimized blog about kitchen gadgets & home improvement."
baseurl: "" # agar repo naam ke saath nahi chalana
url: "https://scottsqualityimprovements.store"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
